### ISSUE TITLE
Wrong data associated to China

### ISSUE THREAD

**Issue by chenx77** [pzhaonet/ncov#16]
Thank you comming back from suspending! I missed your pages:) Seems there is an error in your new page https://ncov2020.org/zh/country-map-2020-03-17/, that the data led by China, sound to be World or Globel (China included): 

1 | China | 中国 | 162236 | 137598 | 6462

Best regards

**Comment by pzhaonet** [comment]
You are right. Fixed. Thank you!

**Comment by chenx77** [comment]
Thank you for swift fixing!
