### ISSUE TITLE
您的项目已录入 OpenSourceWuhan 武汉开源

### ISSUE THREAD

**Issue by WeileiZeng** [pzhaonet/ncov#2]
您好！

感谢您对武汉和开源社区的贡献，您的项目已录入 OpenSourceWuhan 武汉开源,如有疑问请open an issue

武汉开源 OpenSourceWuhan 集齐了开源平台上支援武汉的项目，是一个连结各个开源项目的入口。

站点： https://weileizeng.github.io/OpenSourceWuhan/

附：您有另外一个repo ncovr 不知道您希望我们链接到哪一个库？

**Comment by pzhaonet** [comment]
非常感谢！很好的项目。

ncovr 可以收进 Techniquel tools：

- [pzhaonet/ncovr](https://github.com/pzhaonet/ncovr) R 语言包

**Comment by WeileiZeng** [comment]
谢谢！考虑到两个项目的相关性，我把这个语言包的链接加在了原来的项目后面

**Comment by pzhaonet** [comment]
也行。谢谢！
